### ISSUE TITLE
ListObjectsV2 operation: Access Denied

### ISSUE THREAD

**Issue by davebulaval** [iterative/dvc#6293]
Hi,

I got strange behaviours when upgrading from 2.1.0 to 2.5.0.

On some DVC repo, I get an `unexpected error - _find() got an unexpected keyword argument 'prefix' ` or a `forbidden error 403` on other.

My setup is pretty simple, I have an s3 remote with AWS in each DVC repo and I simply add and push some data. Nothing fancy, no pipeline.

Setup:

Ubuntu 20.10
Python 3.8
DVC 2.1.0 or 2.5.0

**Comment by efiop** [comment]
@davebulaval Could you show `dvc doctor`, please? If you are using pip package, please also show `pip check` and `pip freeze | grep s3fs`

If I had to guess, you are probably using pip package and upgraded dvc without `[s3]` extra, which didn't upgrade `s3fs`. Try:
```
pip install -U 'dvc[s3]'
```
and see if that helps.

**Comment by davebulaval** [comment]
With DVC 2.3.0 I also have a strange `403` error. I have restarted both my DVC repo following the DVC get started tutorial.

**Comment by davebulaval** [comment]
I've tried upgrading dvc[s3] and I still get a `ERROR: unexpected error - Forbidden: An error occurred (403) when calling the HeadObject operation: Forbidden`

**Comment by davebulaval** [comment]
`dvc doctor`

```
DVC version: 2.5.0 (pip)
---------------------------------
Platform: Python 3.8.5 on Linux-5.8.0-59-generic-x86_64-with-glibc2.10
Supports: http, https, s3
Cache types: hardlink, symlink
Cache directory: ext4 on /dev/nvme0n1p3
Caches: local
Remotes: s3
Workspace directory: ext4 on /dev/nvme0n1p3
Repo: dvc, git
```

`pip check`

```
notif 0.5.4 requires notify-run, which is not installed.
textract 1.6.3 has requirement six==1.12.0, but you have six 1.15.0.
extract-msg 0.23.1 has requirement tzlocal==1.5.1, but you have tzlocal 2.1.

```

for the pip freeze and grep.
`s3fs==2021.6.1`

**Comment by davebulaval** [comment]
Note that those results are AFTER upgrading dvc[s3] and I still get the same error (and with 2.1.0 I can push).

**Comment by efiop** [comment]
@davebulaval Could you add `-v` to the command you are running and show full log, please?

**Comment by davebulaval** [comment]
```
dvc push -v
2021-07-06 15:53:17,527 DEBUG: Check for update is enabled.
2021-07-06 15:53:18,005 DEBUG: Preparing to upload data to 's3://plumitifs-storage/datastore'
2021-07-06 15:53:18,006 DEBUG: Preparing to collect status from s3://plumitifs-storage/datastore
2021-07-06 15:53:18,016 DEBUG: Collecting information from local cache...
2021-07-06 15:53:18,121 DEBUG: Collecting information from remote cache...                                                    
2021-07-06 15:53:18,125 DEBUG: Querying 2 hashes via object_exists
2021-07-06 15:53:18,543 ERROR: unexpected error - Forbidden: An error occurred (403) when calling the HeadObject operation: Forbidden
------------------------------------------------------------
Traceback (most recent call last):
  File "/home/despacitov3/anaconda3/envs/py3.8/lib/python3.8/site-packages/s3fs/core.py", line 246, in _call_s3
    out = await method(**additional_kwargs)
  File "/home/despacitov3/anaconda3/envs/py3.8/lib/python3.8/site-packages/aiobotocore/client.py", line 154, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (AccessDenied) when calling the ListObjectsV2 operation: Access Denied

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/despacitov3/anaconda3/envs/py3.8/lib/python3.8/site-packages/s3fs/core.py", line 1057, in _info
    out = await self._simple_info(path)
  File "/home/despacitov3/anaconda3/envs/py3.8/lib/python3.8/site-packages/s3fs/core.py", line 970, in _simple_info
    out = await self._call_s3(
  File "/home/despacitov3/anaconda3/envs/py3.8/lib/python3.8/site-packages/s3fs/core.py", line 265, in _call_s3
    raise translate_boto_error(err)
PermissionError: Access Denied

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/despacitov3/anaconda3/envs/py3.8/lib/python3.8/site-packages/s3fs/core.py", line 246, in _call_s3
    out = await method(**additional_kwargs)
  File "/home/despacitov3/anaconda3/envs/py3.8/lib/python3.8/site-packages/aiobotocore/client.py", line 154, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (403) when calling the HeadObject operation: Forbidden

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/despacitov3/anaconda3/envs/py3.8/lib/python3.8/site-packages/dvc/main.py", line 55, in main
    ret = cmd.do_run()
  File "/home/despacitov3/anaconda3/envs/py3.8/lib/python3.8/site-packages/dvc/command/base.py", line 50, in do_run
    return self.run()
  File "/home/despacitov3/anaconda3/envs/py3.8/lib/python3.8/site-packages/dvc/command/data_sync.py", line 57, in run
    processed_files_count = self.repo.push(
  File "/home/despacitov3/anaconda3/envs/py3.8/lib/python3.8/site-packages/dvc/repo/__init__.py", line 51, in wrapper
    return f(repo, *args, **kwargs)
  File "/home/despacitov3/anaconda3/envs/py3.8/lib/python3.8/site-packages/dvc/repo/push.py", line 44, in push
    pushed += self.cloud.push(objs, jobs, remote=remote)
  File "/home/despacitov3/anaconda3/envs/py3.8/lib/python3.8/site-packages/dvc/data_cloud.py", line 79, in push
    return remote_obj.push(
  File "/home/despacitov3/anaconda3/envs/py3.8/lib/python3.8/site-packages/dvc/remote/base.py", line 57, in wrapper
    return f(obj, *args, **kwargs)
  File "/home/despacitov3/anaconda3/envs/py3.8/lib/python3.8/site-packages/dvc/remote/base.py", line 494, in push
    ret = self._process(
  File "/home/despacitov3/anaconda3/envs/py3.8/lib/python3.8/site-packages/dvc/remote/base.py", line 351, in _process
    dir_status, file_status, dir_contents = self._status(
  File "/home/despacitov3/anaconda3/envs/py3.8/lib/python3.8/site-packages/dvc/remote/base.py", line 191, in _status
    remote_exists.update(self._indexed_dir_hashes(dir_objs))
  File "/home/despacitov3/anaconda3/envs/py3.8/lib/python3.8/site-packages/dvc/remote/base.py", line 258, in _indexed_dir_hashes
    self.odb.list_hashes_exists(indexed_dirs)
  File "/home/despacitov3/anaconda3/envs/py3.8/lib/python3.8/site-packages/dvc/objects/db/base.py", line 389, in list_hashes_exists
    ret = list(itertools.compress(hashes, in_remote))
  File "/home/despacitov3/anaconda3/envs/py3.8/lib/python3.8/concurrent/futures/_base.py", line 611, in result_iterator
    yield fs.pop().result()
  File "/home/despacitov3/anaconda3/envs/py3.8/lib/python3.8/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/home/despacitov3/anaconda3/envs/py3.8/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
  File "/home/despacitov3/anaconda3/envs/py3.8/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/despacitov3/anaconda3/envs/py3.8/lib/python3.8/site-packages/dvc/objects/db/base.py", line 380, in exists_with_progress
    ret = self.fs.exists(path_info)
  File "/home/despacitov3/anaconda3/envs/py3.8/lib/python3.8/site-packages/dvc/fs/fsspec_wrapper.py", line 92, in exists
    return self.fs.exists(self._with_bucket(path_info))
  File "/home/despacitov3/anaconda3/envs/py3.8/lib/python3.8/site-packages/fsspec/asyn.py", line 87, in wrapper
    return sync(self.loop, func, *args, **kwargs)
  File "/home/despacitov3/anaconda3/envs/py3.8/lib/python3.8/site-packages/fsspec/asyn.py", line 68, in sync
    raise result[0]
  File "/home/despacitov3/anaconda3/envs/py3.8/lib/python3.8/site-packages/fsspec/asyn.py", line 24, in _runner
    result[0] = await coro
  File "/home/despacitov3/anaconda3/envs/py3.8/lib/python3.8/site-packages/s3fs/core.py", line 802, in _exists
    await self._info(path, bucket, key, version_id=version_id)
  File "/home/despacitov3/anaconda3/envs/py3.8/lib/python3.8/site-packages/s3fs/core.py", line 1061, in _info
    out = await self._version_aware_info(path, version_id)
  File "/home/despacitov3/anaconda3/envs/py3.8/lib/python3.8/site-packages/s3fs/core.py", line 1004, in _version_aware_info
    out = await self._call_s3(
  File "/home/despacitov3/anaconda3/envs/py3.8/lib/python3.8/site-packages/s3fs/core.py", line 265, in _call_s3
    raise translate_boto_error(err)
PermissionError: Forbidden
------------------------------------------------------------
2021-07-06 15:53:18,641 DEBUG: Version info for developers:
DVC version: 2.5.0 (pip)
---------------------------------
Platform: Python 3.8.5 on Linux-5.8.0-59-generic-x86_64-with-glibc2.10
Supports: http, https, s3
Cache types: hardlink, symlink
Cache directory: ext4 on /dev/nvme0n1p3
Caches: local
Remotes: s3
Workspace directory: ext4 on /dev/nvme0n1p3
Repo: dvc, git

Having any troubles? Hit us up at https://dvc.org/support, we are always happy to help!
2021-07-06 15:53:18,643 DEBUG: Analytics is enabled.
2021-07-06 15:53:18,689 DEBUG: Trying to spawn '['daemon', '-q', 'analytics', '/tmp/tmpsfohfszi']'
2021-07-06 15:53:18,691 DEBUG: Spawned '['daemon', '-q', 'analytics', '/tmp/tmpsfohfszi']'

```

**Comment by efiop** [comment]
@davebulaval Not seeing the `prefix`  error anymore, so looks like the upgrade helped. The current error looks similar to https://github.com/iterative/dvc/issues/5130 . Could you try `aws s3 ls s3://...` with the url of your remote, please?

**Comment by davebulaval** [comment]
```
aws s3 ls s3://plumitifs-storage/datastore
                           PRE datastore/
```

**Comment by davebulaval** [comment]
Note that I was the 403 error for this specific repo, not the prefix, but it fixed for the other one.

**Comment by efiop** [comment]
@davebulaval Are you sure you are using correct keys/profile/etc? Do you have access to the root of that bucket? E.g. does
```
aws s3 ls s3://plumitifs-storage/
```
work?

**Comment by davebulaval** [comment]
Yes, I have the proper key, access, and profile; as I said, everything works like a charm if I downgrade to 2.1.0.

**Comment by daniele-salerno** [comment]
> @davebulaval Not seeing the `prefix` error anymore, so looks like the upgrade helped. The current error looks similar to #5130 . Could you try `aws s3 ls s3://...` with the url of your remote, please?

Don't know why but somehow that command fixed the issue for me

**Comment by efiop** [comment]
@davebulaval @daniele-salerno Btw, guys, are you using aws s3 or some s3-compatible storage?

**Comment by daniele-salerno** [comment]
standard aws s3

**Comment by Kavan72** [comment]
i'm having same problem 
```
(venv) ➜  pdf_api git:(master) dvc push         
ERROR: unexpected error - Forbidden: An error occurred (403) when calling the HeadObject operation: Forbidden                                                                                                                      
Traceback (most recent call last):
  File "s3fs/core.py", line 246, in _call_s3
  File "aiobotocore/client.py", line 154, in _make_api_call
botocore.exceptions.ClientError: An error occurred (AccessDenied) when calling the ListObjectsV2 operation: Access Denied

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "s3fs/core.py", line 1057, in _info
  File "s3fs/core.py", line 970, in _simple_info
  File "s3fs/core.py", line 265, in _call_s3
PermissionError: Access Denied

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "s3fs/core.py", line 246, in _call_s3
  File "aiobotocore/client.py", line 154, in _make_api_call
botocore.exceptions.ClientError: An error occurred (403) when calling the HeadObject operation: Forbidden

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "dvc/main.py", line 55, in main
  File "dvc/command/base.py", line 50, in do_run
  File "dvc/command/data_sync.py", line 57, in run
  File "dvc/repo/__init__.py", line 51, in wrapper
  File "dvc/repo/push.py", line 44, in push
  File "dvc/data_cloud.py", line 79, in push
  File "dvc/remote/base.py", line 57, in wrapper
  File "dvc/remote/base.py", line 494, in push
  File "dvc/remote/base.py", line 351, in _process
  File "dvc/remote/base.py", line 195, in _status
  File "dvc/remote/base.py", line 145, in hashes_exist
  File "dvc/objects/db/base.py", line 438, in hashes_exist
  File "dvc/objects/db/base.py", line 389, in list_hashes_exists
  File "concurrent/futures/_base.py", line 611, in result_iterator
  File "concurrent/futures/_base.py", line 439, in result
  File "concurrent/futures/_base.py", line 388, in __get_result
  File "concurrent/futures/thread.py", line 57, in run
  File "dvc/objects/db/base.py", line 380, in exists_with_progress
  File "dvc/fs/fsspec_wrapper.py", line 92, in exists
  File "fsspec/asyn.py", line 87, in wrapper
  File "fsspec/asyn.py", line 68, in sync
  File "fsspec/asyn.py", line 24, in _runner
  File "s3fs/core.py", line 802, in _exists
  File "s3fs/core.py", line 1061, in _info
  File "s3fs/core.py", line 1004, in _version_aware_info
  File "s3fs/core.py", line 265, in _call_s3
PermissionError: Forbidden

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "dvc/__main__.py", line 7, in <module>
  File "dvc/main.py", line 88, in main
  File "dvc/info.py", line 35, in get_dvc_info
  File "dvc/info.py", line 127, in _get_supported_remotes
  File "importlib/metadata.py", line 531, in version
  File "importlib/metadata.py", line 504, in distribution
  File "importlib/metadata.py", line 177, in from_name
importlib.metadata.PackageNotFoundError: adlfs
[20135] Failed to execute script __main__
```
in my case. i'm a owner of my bucket so there is no perm issue i guess. and also aws ls is als working
![image](https://user-images.githubusercontent.com/19048640/126153777-4918c75e-ca25-4445-867e-928cc59d2fbf.png)

**Comment by efiop** [comment]
@Kavan72 Could you show `dvc doctor` output, please?

**Comment by Kavan72** [comment]
yep sure @efiop 
```
DVC version: 2.5.4 (pip)
---------------------------------
Platform: Python 3.8.10 on Linux-5.8.0-59-generic-x86_64-with-glibc2.29
Supports:
        azure (adlfs = 0.7.1, knack = 0.8.2, azure-identity = 1.6.0),
        gdrive (pydrive2 = 1.8.3),
        gs (gcsfs = 2021.6.1),
        hdfs (pyarrow = 4.0.1),
        webhdfs (hdfs = 2.5.8),
        http (requests = 2.26.0),
        https (requests = 2.26.0),
        s3 (s3fs = 2021.6.1, boto3 = 1.17.49),
        ssh (paramiko = 2.7.2),
        oss (oss2 = 2.6.1),
        webdav (webdav4 = 0.8.2),
        webdavs (webdav4 = 0.8.2)
Cache types: hardlink, symlink
Cache directory: fuseblk on /dev/sda2
Caches: local
Remotes: s3
Workspace directory: fuseblk on /dev/sda2
Repo: dvc, git
```

**Comment by Kavan72** [comment]
Some how `set_session` is not getting `aws_access_key_id` and `aws_secret_access_key`
![image](https://user-images.githubusercontent.com/19048640/126158186-599f4376-17fb-4dd0-9812-3233b6a8f231.png)
 check output 
 
![image](https://user-images.githubusercontent.com/19048640/126158243-bff0460d-c9f9-4e98-9412-f531fa3ddf1e.png)

**Comment by efiop** [comment]
@Kavan72 That looks incorrect, the first log is coming from a binary package (deb or rpm or osxpkg), while the latter one is from pip package. Are you getting the same error with pip package too?

**Comment by Kavan72** [comment]
yes, first i've installed binary package and for some downgrade testing i removed binary package and installed from pip, but getting same error

**Comment by Kavan72** [comment]
okay, after some downgrade testing working on `2.1.0`. and next version(2.2.0) it stop working

**Comment by davebulaval** [comment]
> okay, after some downgrade testing working on `2.1.0`. and next version(2.2.0) it stop working

Similar to me. Also on standard AWS s3 bucket.

**Comment by efiop** [comment]
Thanks for the feedback guys! We'll take a closer look, seems like this might be a bug `s3fs`.

**Comment by efiop** [comment]
Btw, @Kavan72 @davebulaval @daniele-salerno Could you try running:

```
aws s3api list-objects-v2 --bucket my-bucket
```

? Just making sure you have permissions to use listobjectsv2.

**Comment by davebulaval** [comment]
> Btw, @Kavan72 @davebulaval @daniele-salerno Could you try running:
> 
> ```
> aws s3api list-objects-v2 --bucket my-bucket
> ```
> 
> ? Just making sure you have permission to use listobjectsv2.

What is the expected output? I get a JSON file with a key "contents" and the value is a list of `dict` with 4 keys/values.

**Comment by Kavan72** [comment]
> Btw, @Kavan72 @davebulaval @daniele-salerno Could you try running:
> 
> ```
> aws s3api list-objects-v2 --bucket my-bucket
> ```
> 
> ? Just making sure you have permissions to use listobjectsv2.

yes working 

```
{
    "Contents": [
        {
            "Key": "pdf_extractor_models/",
            "LastModified": "2021-07-19T10:36:42+00:00",
            "ETag": "\"d41d8cd98f00b204e9800998ecf8427e\"",
            "Size": 0,
            "StorageClass": "STANDARD"
        },
        {
            "Key": "pdf_extractor_models/46/671b32efd11065dd23658f78ba9f09",
            "LastModified": "2021-07-19T12:47:16+00:00",
            "ETag": "\"2f6bf9f23d4469fa07427bb7f0560d0d-2\"",
            "Size": 14385567,
            "StorageClass": "STANDARD"
        }
    ]
}
```

**Comment by Kavan72** [comment]
> > Btw, @Kavan72 @davebulaval @daniele-salerno Could you try running:
> > ```
> > aws s3api list-objects-v2 --bucket my-bucket
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ? Just making sure you have permission to use listobjectsv2.
> 
> What is the expected output? I get a JSON file with a key "contents" and the value is a list of `dict` with 4 keys/values.

yes that the expected output

**Comment by efiop** [comment]
Thanks! Ok, so something more complex is going on then. Will need to take a closer look.

CC @isidentical maybe you've run into this before.

**Comment by davebulaval** [comment]
Working with DVC 2.6.3 and s3 updated now.

Will close the issue.
