### ISSUE TITLE
dvc exp run failing in v1.10

### ISSUE THREAD

**Issue by dberenbaum** [iterative/dvc#4959]
## Bug Report

`dvc exp run --params p=1` outputs:

`ERROR: Failed to reproduce experiment '8e78710' - failed to reproduce 'dvc.yaml': restore() got an unexpected keyword argument 'checkpoint_resume'`

The same command works in 1.9.0.

This is a toy example with no checkpoints:

```
#!/usr/bin/env python
"""
Test experiment for DVC.
"""

import os
import yaml


def main():
    output_file = "foo"
    metrics_file = "metrics.yaml"

    with open("params.yaml") as fobj:
        params = yaml.load(fobj)
    p = params["p"]

    with open(output_file, "w") as fobj:
        fobj.write(f"{p}")

    with open(metrics_file, "w") as fobj:
        yaml.dump(params, fobj)


if __name__ == "__main__":
    main()
```

### Please provide information about your setup

**Output of `dvc version`:**

```console
$ dvc version
DVC version: 1.10.1 (pip)
---------------------------------
Platform: Python 3.8.5 on Linux-4.17.5-1-ARCH-x86_64-with-glibc2.10
Supports: http, https
Cache types: hardlink, symlink
Caches: local
Remotes: None
Repo: dvc, git
```

**Additional Information (if any):**

If applicable, please also provide a `--verbose` output of the command, eg: `dvc add --verbose`.

**Comment by efiop** [comment]
Hi @dberenbaum !

This bug was fixed in https://github.com/iterative/dvc/pull/4913 thanks to @sjawhar :pray: , but we didn't release a new version yet :slightly_frowning_face: We are releasing 1.10.2 right now, will be available on pypi in ~15minutes.

Also, just a friendly disclaimer that experiments are an experimental feature and haven't been officially released yet, so there might be some bugs/changes and you are using it at your own risk. :slightly_smiling_face: 

Thanks for the feedback!
