### ISSUE TITLE
Traceback relating to fsspec

### ISSUE THREAD

**Issue by verdurin** [iterative/dvc#10721]
# Bug Report

## Issue name

dvc --version: traceback with LocalFileSystem object

## Description

I am writing an EasyBuild easyconfig so DVC can be installed on HPC clusters.

As part of the easyconfig, once all the Python extensions including dvc have been installed, it runs "sanity check commands" to confirm basic functionality of the application. In this case the commands are:

`dvc --version && dvc doctor`

This causes an error:

`ERROR: unexpected error - 'LocalFileSystem' object has no attribute 'abspath'`

and a traceback (shown below).

We think this relates to the version of `fsspec`, which in the `pyproject.toml` is pinned to `2024.2.0`.

### Reproduce

dvc --version && dvc doctor

### Expected

The dvc version is shown and the `dvc doctor` output is shown.

### Environment information

The build host is running Rocky 8.10, the Python version is 3.11.3 from EasyBuild.
Here are the high-level dependencies in use:
```
    ('Python', '3.11.3'),
    ('git', '2.41.0', '-nodocs'),
    ('GitPython', '3.1.40'),
    ('networkx', '3.1'),
    ('PyYAML', '6.0'),
    ('ruamel.yaml', '0.17.32'),
    ('SciPy-bundle', '2023.07'),
    ('tqdm', '4.66.1'),
    ('pydantic', '2.5.3'),
```

**Output of `dvc doctor`:**

This is one of the failing commands, so I can't show the output.

**Additional Information (if any):**

It seems that there have been changes in `fsspec` which this version of `dvc` hasn't been modified to account for.

Here is the `2024.2.0` traceback:
```
ERROR: unexpected error - 'LocalFileSystem' object has no attribute 'abspath'

Having any troubles? Hit us up at https://dvc.org/support, we are always happy to help!
Traceback (most recent call last):
  File "/apps/eb/el8/upstream/software/dvc/3.59.1-gfbf-2023a/bin/dvc", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/apps/eb/el8/upstream/software/dvc/3.59.1-gfbf-2023a/lib/python3.11/site-packages/dvc/cli/__init__.py", line 243, in main
    if analytics.is_enabled():
       ^^^^^^^^^^^^^^^^^^^^^^
  File "/apps/eb/el8/upstream/software/dvc/3.59.1-gfbf-2023a/lib/python3.11/site-packages/dvc/analytics.py", line 53, in is_enabled
    Config.from_cwd(validate=False).get("core", {}).get("analytics", "true")
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/apps/eb/el8/upstream/software/dvc/3.59.1-gfbf-2023a/lib/python3.11/site-packages/dvc/config.py", line 126, in from_cwd
    dvc_dir = Repo.find_dvc_dir(fs=fs)
              ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/apps/eb/el8/upstream/software/dvc/3.59.1-gfbf-2023a/lib/python3.11/site-packages/dvc/repo/__init__.py", line 438, in find_dvc_dir
    root_dir = cls.find_root(root, fs=fs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/apps/eb/el8/upstream/software/dvc/3.59.1-gfbf-2023a/lib/python3.11/site-packages/dvc/repo/__init__.py", line 410, in find_root
    root_dir = fs.abspath(root)
               ^^^^^^^^^^
AttributeError: 'LocalFileSystem' object has no attribute 'abspath'
```

I have tried changing to earlier versions of `fsspec` and they cause different tracebacks e.g.:
```
== FAILED: Installation ended unsuccessfully: Sanity check failed: sanity check command dvc --version && dvc doctor failed with exit code 1 (output: 3.59.1
Traceback (most recent call last):
  File "/apps/eb/el8/upstream/software/dvc/3.59.1-gfbf-2023a/lib/python3.11/site-packages/dvc/cli/__init__.py", line 211, in main
    ret = cmd.do_run()
          ^^^^^^^^^^^^
  File "/apps/eb/el8/upstream/software/dvc/3.59.1-gfbf-2023a/lib/python3.11/site-packages/dvc/cli/command.py", line 41, in do_run
    return self.run()
           ^^^^^^^^^^
  File "/apps/eb/el8/upstream/software/dvc/3.59.1-gfbf-2023a/lib/python3.11/site-packages/dvc/commands/version.py", line 12, in run
    from dvc.info import get_dvc_info
  File "/apps/eb/el8/upstream/software/dvc/3.59.1-gfbf-2023a/lib/python3.11/site-packages/dvc/info.py", line 11, in <module>
    from dvc.fs import Schemes, generic, get_fs_cls, get_fs_config, registry
  File "/apps/eb/el8/upstream/software/dvc/3.59.1-gfbf-2023a/lib/python3.11/site-packages/dvc/fs/__init__.py", line 30, in <module>
    from .callbacks import Callback  # noqa: F401
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/apps/eb/el8/upstream/software/dvc/3.59.1-gfbf-2023a/lib/python3.11/site-packages/dvc/fs/callbacks.py", line 5, in <module>
    from fsspec.callbacks import DEFAULT_CALLBACK, Callback  # noqa: F401
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ImportError: cannot import name 'DEFAULT_CALLBACK' from 'fsspec.callbacks' (/apps/eb/el8/upstream/software/dvc/3.59.1-gfbf-2023a/lib/python3.11/site-packages/fsspec/callbacks.py)
```

That is with `fsspec` `2022.11.0`.

**Comment by skshetry** [comment]
Hi, can you share the output of `pip show dvc-objects dvc-data fsspec`?

**Comment by verdurin** [comment]
Hello - not sure I can do that, given the module build doesn't complete so there's no

However, here are the versions of those in the easyconfig:

`dvc-objects` - `1.0.1`
`dvc-data` - `3.16.2`
`fsspec` - `2023.12.2`

So far I've had to tweak the versions of many of these extensions for the build with `Python` `3.11`.

**Comment by verdurin** [comment]
Yes, I'll try with newer version, thanks.

However, I already saw that I can't use very recent `dvc-data` because then I see this error:
```
Using pip 23.1.2 from /apps/eb/el8/upstream/software/Python/3.11.3-GCCcore-12.3.0/lib/python3.11/site-packages/pip (python 3.11)
Processing /dev/shm/dvc/3.59.1/gfbf-2023a/dvcdata/dvc_data-3.16.8
  Preparing metadata (pyproject.toml): started
  Running command Preparing metadata (pyproject.toml)
  configuration error: `project.classifiers[5]` must be trove-classifier
  DESCRIPTION:
      `PyPI classifier <https://pypi.org/classifiers/>`_.

  GIVEN VALUE:
      "Programming Language :: Python :: 3.13"

  OFFENDING RULE: 'format'

  DEFINITION:
      {
          "type": "string",
          "format": "trove-classifier"
      }
```

**Comment by skshetry** [comment]
You likely have an older version of `trove_classifiers` installed which is used by `setuptools`
(older than [2023.8.7](https://github.com/pypa/trove-classifiers/releases/tag/2023.8.7).

It looks like there is an envvar to disable this validation that you can use, see https://github.com/pypa/setuptools/pull/4611.

I can't really help you more than that here as it is not related to dvc. So you will have to figure out yourself.

I am closing the issue.

**Comment by verdurin** [comment]
Many thanks, this has helped a lot. I've added `trove_classifiers` to the recipe, and that problem is fixed. I'm now going through and updating various other extensions.
