### PR TITLE
render.match: Skip errored revisions in `get_files`

### PR DESCRIPTION
**Pull request by daavoo**
Introduced in #7409

### CODE REVIEW

File: dvc/render/match.py [hunk 1]
```diff
@@ -10,8 +10,12 @@
 
 
 def get_files(plots_data: Dict) -> List:
-    values = dpath.util.values(plots_data, ["*", "*"])
-    return sorted({key for submap in values for key in submap.keys()})
```
Comment (daavoo) [inline dvc/render/match.py:14]: When a error happens during collection, `values` would be:

```
{"error": ResolveError}
```
And the removed code would fail with:

```
AttributeError: 'ResolveError' object has no attribute 'keys'
```

**Review by pared — APPROVED** [review]
