### ISSUE TITLE
http remote broken

### ISSUE THREAD

**Issue by dtrifiro** [iterative/dvc#7666]
Changes introduced in https://github.com/iterative/dvc/pull/7649 (add atomic upload function) [are breaking](https://github.com/iterative/dvc-http/runs/6237130209?check_suite_focus=true#step:8:675) http remotes because fsspec's `HTTPFileSystem` does not implement `_cp_file`.

**Comment by efiop** [comment]
And looks like we triggered a "is subject to bucket's retention policy and cannot be deleted, overwritten or archived until" error in gs. Reverting for now.

**Comment by dtrifiro** [comment]
Closing this as the change has been reverted.
cc @skshetry

**Comment by efiop** [comment]
Let's keep it open for now.

**Comment by efiop** [comment]
Discussed with @skshetry that there are more problems with the previous PR, so we could just close for now
