### ISSUE TITLE
dvc push: "ERROR: unexpected error - 'AioClientCreator' object has no attribute '_register_lazy_block_unknown_fips_pseudo_regions' "

### ISSUE THREAD

**Issue by Guillaume-oso** [iterative/dvc#7053]
# Bug Report

## Description

Hi,
I get this error: 
ERROR: unexpected error - 'AioClientCreator' object has no attribute '_register_lazy_block_unknown_fips_pseudo_regions' 

when I try to execute dvc push.

### Reproduce

To reproduce the error, push to S3 after a "dvc repro", with these versions.

I got this error many times on different git repositories.

### Environment information

I work with ubuntu 20.04
I installed dvc with pip 20.0.2 in a virtual environnement (virtualenv==20.8.1)
dvc version: dvc[s3]==2.7.4
git version 2.25.1
boto3==1.20.13
s3fs==2021.11.0

**Output of `dvc doctor`:**

DVC version: 2.7.4 (pip)
---------------------------------
Platform: Python 3.8.10 on Linux-5.8.0-38-generic-x86_64-with-glibc2.29
Supports:
        http (aiohttp = 3.8.1, aiohttp-retry = 2.4.5),
        https (aiohttp = 3.8.1, aiohttp-retry = 2.4.5),
        s3 (s3fs = 2021.11.0, boto3 = 1.20.13)
Cache types: hardlink, symlink
Cache directory: ext4 on /dev/nvme0n1p2
Caches: local
Remotes: s3
Workspace directory: ext4 on /dev/nvme0n1p2
Repo: dvc, git

**Comment by efiop** [comment]
Hi @Guillaume-oso Please run `dvc push -v` and show us full log.

**Comment by Guillaume-oso** [comment]
(.venv) guillaume@server:~/stress$ dvc push -v
2021-11-25 22:14:35,121 DEBUG: Preparing to transfer data from '.dvc/cache' to 's3://oso-dvc'
2021-11-25 22:14:35,122 DEBUG: Preparing to collect status from 's3://oso-dvc'
2021-11-25 22:14:35,122 DEBUG: Collecting status from 's3://oso-dvc'
2021-11-25 22:14:35,122 DEBUG: Querying 2 hashes via object_exists
2021-11-25 22:14:35,187 ERROR: unexpected error - 'AioClientCreator' object has no attribute '_register_lazy_block_unknown_fips_pseudo_regions'                                                                                      
------------------------------------------------------------
Traceback (most recent call last):
  File "/home/guillaume/stress/.venv/lib/python3.8/site-packages/dvc/main.py", line 55, in main
    ret = cmd.do_run()
  File "/home/guillaume/stress/.venv/lib/python3.8/site-packages/dvc/command/base.py", line 45, in do_run
    return self.run()
  File "/home/guillaume/stress/.venv/lib/python3.8/site-packages/dvc/command/data_sync.py", line 57, in run
    processed_files_count = self.repo.push(
  File "/home/guillaume/stress/.venv/lib/python3.8/site-packages/dvc/repo/__init__.py", line 50, in wrapper
    return f(repo, *args, **kwargs)
  File "/home/guillaume/stress/.venv/lib/python3.8/site-packages/dvc/repo/push.py", line 56, in push
    pushed += self.cloud.push(
  File "/home/guillaume/stress/.venv/lib/python3.8/site-packages/dvc/data_cloud.py", line 85, in push
    return transfer(
  File "/home/guillaume/stress/.venv/lib/python3.8/site-packages/dvc/objects/transfer.py", line 153, in transfer
    status = compare_status(src, dest, obj_ids, check_deleted=False, **kwargs)
  File "/home/guillaume/stress/.venv/lib/python3.8/site-packages/dvc/objects/status.py", line 160, in compare_status
    dest_exists, dest_missing = status(
  File "/home/guillaume/stress/.venv/lib/python3.8/site-packages/dvc/objects/status.py", line 122, in status
    exists = hashes.intersection(
  File "/home/guillaume/stress/.venv/lib/python3.8/site-packages/dvc/objects/status.py", line 36, in _indexed_dir_hashes
    indexed_dir_exists.update(odb.list_hashes_exists(indexed_dirs))
  File "/home/guillaume/stress/.venv/lib/python3.8/site-packages/dvc/objects/db/base.py", line 419, in list_hashes_exists
    ret = list(itertools.compress(hashes, in_remote))
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 619, in result_iterator
    yield fs.pop().result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 444, in result
    return self.__get_result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/guillaume/stress/.venv/lib/python3.8/site-packages/dvc/objects/db/base.py", line 410, in exists_with_progress
    ret = self.fs.exists(path_info)
  File "/home/guillaume/stress/.venv/lib/python3.8/site-packages/dvc/fs/fsspec_wrapper.py", line 136, in exists
    return self.fs.exists(self._with_bucket(path_info))
  File "/home/guillaume/stress/.venv/lib/python3.8/site-packages/fsspec/asyn.py", line 91, in wrapper
    return sync(self.loop, func, *args, **kwargs)
  File "/home/guillaume/stress/.venv/lib/python3.8/site-packages/fsspec/asyn.py", line 71, in sync
    raise return_result
  File "/home/guillaume/stress/.venv/lib/python3.8/site-packages/fsspec/asyn.py", line 25, in _runner
    result[0] = await coro
  File "/home/guillaume/stress/.venv/lib/python3.8/site-packages/s3fs/core.py", line 822, in _exists
    await self._info(path, bucket, key, version_id=version_id)
  File "/home/guillaume/stress/.venv/lib/python3.8/site-packages/s3fs/core.py", line 1016, in _info
    out = await self._call_s3(
  File "/home/guillaume/stress/.venv/lib/python3.8/site-packages/s3fs/core.py", line 241, in _call_s3
    await self.set_session()
  File "/home/guillaume/stress/.venv/lib/python3.8/site-packages/s3fs/core.py", line 404, in set_session
    self._s3 = await s3creator.get_client()
  File "/home/guillaume/stress/.venv/lib/python3.8/site-packages/s3fs/utils.py", line 92, in get_client
    self._client = await self._stack.enter_async_context(
  File "/usr/lib/python3.8/contextlib.py", line 568, in enter_async_context
    result = await _cm_type.__aenter__(cm)
  File "/home/guillaume/stress/.venv/lib/python3.8/site-packages/aiobotocore/session.py", line 37, in __aenter__
    self._client = await self._coro
  File "/home/guillaume/stress/.venv/lib/python3.8/site-packages/aiobotocore/session.py", line 121, in _create_client
    client = await client_creator.create_client(
  File "/home/guillaume/stress/.venv/lib/python3.8/site-packages/aiobotocore/client.py", line 46, in create_client
    self._register_lazy_block_unknown_fips_pseudo_regions(service_client)
AttributeError: 'AioClientCreator' object has no attribute '_register_lazy_block_unknown_fips_pseudo_regions'
------------------------------------------------------------
2021-11-25 22:14:35,232 DEBUG: Version info for developers:
DVC version: 2.8.3 (pip)
---------------------------------
Platform: Python 3.8.10 on Linux-5.8.0-38-generic-x86_64-with-glibc2.29
Supports:
        webhdfs (fsspec = 2021.11.0),
        http (aiohttp = 3.8.1, aiohttp-retry = 2.4.6),
        https (aiohttp = 3.8.1, aiohttp-retry = 2.4.6),
        s3 (s3fs = 2021.11.0, boto3 = 1.20.13)
Cache types: hardlink, symlink
Cache directory: ext4 on /dev/nvme0n1p2
Caches: local
Remotes: s3
Workspace directory: ext4 on /dev/nvme0n1p2
Repo: dvc, git

Having any troubles? Hit us up at https://dvc.org/support, we are always happy to help!
2021-11-25 22:14:35,233 DEBUG: Analytics is enabled.
2021-11-25 22:14:35,257 DEBUG: Trying to spawn '['daemon', '-q', 'analytics', '/tmp/tmpqtr4qlw5']'
2021-11-25 22:14:35,258 DEBUG: Spawned '['daemon', '-q', 'analytics', '/tmp/tmpqtr4qlw5']'

**Comment by Guillaume-oso** [comment]
this is not the same version here, but the error appears for versions:
2.8.4, 2.8.3, 2.7.4, etc

**Comment by Guillaume-oso** [comment]
Here is the same command but outside the virtual environment:

guillaume@server:~/stress$ dvc push -v                                                                                                                                                                                           
2021-11-25 22:25:43,244 DEBUG: Preparing to transfer data from '.dvc/cache' to 's3://oso-dvc'                                                                                                                                        
2021-11-25 22:25:43,245 DEBUG: Preparing to collect status from 's3://oso-dvc'                                                                                                                                                       
2021-11-25 22:25:43,245 DEBUG: Collecting status from 's3://oso-dvc'                                                                                                                                                                 
2021-11-25 22:25:43,245 DEBUG: Querying 4 hashes via object_exists                                                                                                                                                                   
2021-11-25 22:25:43,692 DEBUG: Querying 0 hashes via object_exists                                                                                                                                                                   
2021-11-25 22:25:43,729 DEBUG: Estimated remote size: 8192 files                                                                                                                                                                     
2021-11-25 22:25:43,730 DEBUG: Querying '11' hashes via traverse                                                                                                                                                                     
Everything is up to date.                                                                                                                                                                                                            
2021-11-25 22:25:46,090 DEBUG: Analytics is enabled.
2021-11-25 22:25:46,113 DEBUG: Trying to spawn '['daemon', '-q', 'analytics', '/tmp/tmprgmwo4v8']'
2021-11-25 22:25:46,116 DEBUG: Spawned '['daemon', '-q', 'analytics', '/tmp/tmprgmwo4v8']'
guillaume@server:~/stress$ dvc doctor
DVC version: 2.8.3 (pip)
---------------------------------


Platform: Python 3.8.10 on Linux-5.8.0-38-generic-x86_64-with-glibc2.29
Supports:
        webhdfs (fsspec = 2021.11.0),
        http (aiohttp = 3.8.0, aiohttp-retry = 2.4.6),
        https (aiohttp = 3.8.0, aiohttp-retry = 2.4.6),
        s3 (s3fs = 2021.11.0, boto3 = 1.17.106)
Cache types: hardlink, symlink
Cache directory: ext4 on /dev/nvme0n1p2
Caches: local
Remotes: s3
Workspace directory: ext4 on /dev/nvme0n1p2
Repo: dvc, git

**Comment by Guillaume-oso** [comment]
looks like it comes from boto3 version instead of virtual environment

**Comment by Guillaume-oso** [comment]
After few tests, I noticed that push does not work for boto3 versions >=1.20.0

**Comment by ryanmjacobs** [comment]
I was also unable to push, but running `pip install boto==1.19.12` did the trick. Works fine for me now.

Exact same error: ` ERROR: unexpected error - 'AioClientCreator' object has no attribute '_register_lazy_block_unknown_fips_pseudo_regions'`

**Comment by Guillaume-oso** [comment]
an other precision:
does not work for boto3 versions > 1.19.12 only if coupled with s3fs==2021.11.0

works again if s3fs==2021.11.1

**Comment by efiop** [comment]
@Guillaume-oso Thanks for the research! Bumped s3fs requirements in upstream, 2.9.2 should come out with it fixed.
